# Generated by Django 5.2.6 on 2025-10-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
