# Generated by Django 5.2.6 on 2025-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_profile_avatar_profile_bank_account_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_type',
            field=models.CharField(blank=True, choices=[('nid', 'National ID / NID card'), ('passport', 'Passport'), ('driver_license', "Driver's license"), ('utility_bill', 'Recent utility bill or bank statement (address proof)')], max_length=50),
        ),
    ]
