# Generated by Django 5.2.6 on 2025-10-05 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_update_approved_at_update_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investment',
            name='gateway_event_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('bkash', 'bKash')], default='bkash', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('gateway_event_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invest.investment')),
            ],
        ),
    ]
