# Generated by Django 5.2.6 on 2025-10-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0007_investment_gateway_investment_gateway_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(blank=True, max_length=50)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('raw_payload', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=500)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='invest.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['gateway', 'event_id'], name='invest_webh_gateway_bb9f82_idx')],
            },
        ),
    ]
