# Generated by Django 5.2.6 on 2025-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='risk_grade',
            field=models.CharField(choices=[('A', 'A - Low'), ('B', 'B - Moderate'), ('C', 'C - Medium'), ('D', 'D - High'), ('E', 'E - Very High')], default='C', max_length=1),
        ),
    ]
